#-------------------------------
## General Site Settings

owner:
  name: "Jingle Jam"
  email: charles.cabral.neto@gmail.com
  social:
    - {icon: 'twitter', link: 'http://twitter.com/charlescabral'}
    - {icon: 'linkedin', link: 'http://www.linkedin.com/in/charlescabral/'}



djs:  
- {name: 'OLSEN [LouLou Records/MAZE]' , slug: olsen, link: 'https://soundcloud.com/olsenneto'}
- {name: 'D.O.P.E', slug: dope, link: 'https://soundcloud.com/itsdopemusic'}
- {name: 'Pan.tufo', slug: pan-tufo, link: ''}
- {name: 'JU URIZZI [House of Stage]', slug: ju-urizzi, link: 'https://soundcloud.com/juurizzi'}
- {name: 'THI MARQUES [Coyote Crew]', slug: thi-marques, link: 'https://soundcloud.com/thi-marques'}
- {name: 'FRANCISCO A. [Coyote Crew]', slug: francisco-a, link: 'https://soundcloud.com/francisco-arranz'}
- {name: 'LUCAS EROLES', slug: lucas-eroles, link: 'https://soundcloud.com/lucaseroles'}
- {name: 'LÉO ØLIVEIRA [Balearic]', slug: leo-oliveira, link: 'https://soundcloud.com/leooliverradj'}


#-------------------------------
# Projects
projects:
  path: '/assets/img/projects/' 
# - title: Webdesign
#   folder: web

# - title: Branding
#   folder: brand

# - title: Coding
#   folder: code


# SEO Section
# google:
  # ad-client: ca-pub-7328585512091257
  # ad-slot: 3049671934
  # analytics: UA-2011187-1
  # plus: https://plus.google.com/+MichaelRoseDesign/posts
  # verify: geapSKtvpBNDSfXVmF09E9CnaHGglbO61r4XgLZtEmo
  

