#-------------------------------
## General Site Settings

owner:
  name: "Jingle Jam"
  email: charles.cabral.neto@gmail.com
  social:s
    - {icon: 'twitter', link: 'http://twitter.com/charlescabral'}
    - {icon: 'linkedin', link: 'http://www.linkedin.com/in/charlescabral/'}


#-------------------------------
# Projects
projects:
  path: '/assets/img/projects/' 
# - title: Webdesign
#   folder: web

# - title: Branding
#   folder: brand

# - title: Coding
#   folder: code


# SEO Section
# google:
  # ad-client: ca-pub-7328585512091257
  # ad-slot: 3049671934
  # analytics: UA-2011187-1
  # plus: https://plus.google.com/+MichaelRoseDesign/posts
  # verify: geapSKtvpBNDSfXVmF09E9CnaHGglbO61r4XgLZtEmo
  

