#-------------------------------
## General Site Settings

owner:
  name: "Charles Cabral"
  email: charles.cabral.neto@gmail.com
  bio: "Just another boring, musician, time traveling designer."
  avatar: layout/travitar.jpg
  disqus-shortname: Charles
  social:
    - {icon: 'twitter', link: 'http://twitter.com/charlescabral'}
    - {icon: 'linkedin', link: 'http://www.linkedin.com/in/charlescabral/'}

#-------------------------------
# About Section
skills:  
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '7'}
- {name: Visual Design, value: '10'}
- {name: UX Design, value: '8'}
- {name: Programming, value: '6'}
#-------------------------------




#-------------------------------
# Projects
projects:
  path: '/assets/img/projects/' 
# - title: Webdesign
#   folder: web

# - title: Branding
#   folder: brand

# - title: Coding
#   folder: code


# SEO Section
# google:
  # ad-client: ca-pub-7328585512091257
  # ad-slot: 3049671934
  # analytics: UA-2011187-1
  # plus: https://plus.google.com/+MichaelRoseDesign/posts
  # verify: geapSKtvpBNDSfXVmF09E9CnaHGglbO61r4XgLZtEmo
  

